[build]
  command = "cd frontend && npm install && npm run generate"
  publish = "frontend/.output/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["config/config.json"]

[dev]
  command = "cd frontend && npm install && npm run dev"
  targetPort = 3000
  port = 8888
  publish = "frontend/.output/public"


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
