[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/.output/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["config/config.json"]

[dev]
  command = "npm run dev --prefix frontend"
  targetPort = 3000
  port = 8888
  publish = "frontend/.output/public"
